name: integration

on: 
  pull_request:
    branches: [ master ]
jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          reposiroty: ${{ github.pocwebdriverio }}
      - run: npm ci
      - run: npm run wdio
      - run: npm run report